#!/usr/bin/env bash

# forked from rofi-power by Oliver Kraitschy - http://okraits.de

# Use wofi to call systemctl for shutdown, reboot, etc

OPTIONS="Lock system\nReboot system\nPower-off system\nSuspend system\nHibernate system"

LAUNCHER="wofi --width 480 --height 320 --dmenu -i -p wofi-power:"

USE_LOCKER="false"

LOCKER="swaylock"

# Show exit wm option if exit command is provided as an argument
if [ ${#1} -gt 0 ]; then
    OPTIONS="Exit window manager\n$OPTIONS"
fi

option=`echo -e $OPTIONS | $LAUNCHER | awk '{print $1}' | tr -d '\r\n'`

if [ ${#option} -gt 0 ]
then
    case $option in
        Exit)
            eval $1
            ;;
        Reboot)
            systemctl reboot
            ;;
        Power-off)
            systemctl poweroff
            ;;
        Suspend)
            $($USE_LOCKER) && "$LOCKER"; systemctl suspend
            ;;
        Hibernate)
            $($USE_LOCKER) && "$LOCKER"; systemctl hibernate
            ;;
        Lock)
            "$LOCKER"
            ;;
        *)
        ;;
    esac
fi
